# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Booking.destroy_all
Politic.destroy_all
User.destroy_all


usertest = User.create!(email: "abc@gmail.com", password: "tototo")
user2 = User.create!(email: "xyz@gmail.com", password: "tototo")

trump = Politic.create!(name: "Trump", country: "USA", description: "I'm Intelligent, some people say I'm very very very Intelligent!", picture: "https://pagtour.info/wp-content/uploads/2018/09/img-coupe-du-monde-2026-donald-trump-met-un-gros-coup-de-pression-1524824401_x600_articles-454974-2.jpg",
  address: "1600 Pennsylvania Avenue NW", first_stupid: "fake news!", second_stupid: "America first", availability: true, rating: 5, user: usertest)
sarkozy = Politic.create(name: "Sarkozy", country: "France", description: "Longue expérience en gestion de projet et évènementiel, expertise en financements de campagnes", picture: "https://cdn.radiofrance.fr/s3/cruiser-production/2017/01/c4314dc8-b0ca-4989-be12-0562125ba76f/838_kadhafi_et_nicolas_sarkozy_en_libye_juillet_2007_cpatrick_kovarik_afp.jpg",
  address: "99 Av. des Champs-Élysées, 75008 Paris", first_stupid: "Si t'as pas une Rollex à 50 ans, t'as raté ta vie", second_stupid: "Casse toi pauv' con", availability: true, rating: 4, user: usertest)
fillon = Politic.create(name: "Fillon", country: "France", description: "Aujourd'hui retraité de la fonction publique, je partage ma passion pour le textile et la fiction aux plus ambitieux", picture: "https://file1.closermag.fr/var/closermag/storage/images/media/images-des-contenus/article/2017-01-25-penelope-fillon-dans-la-tourmente-les-internautes-se-moquent-de-la-femme-de-francois-fillon/france-angleterre-tournoi-des-vi-nations-2012-penelope-et-francois-fillon-paris-le-11-03-2012/5594250-1-fre-FR/France-Angleterre-Tournoi-des-VI-Nations-2012-Penelope-et-Francois-Fillon-Paris-le-11-03-2012.jpg?alias=original",
  address:"Parking lot, Ulitsa Okhotnyy Ryad, 2, Moscow, Russie, 125009", first_stupid: "Vous auriez la veste en L?", second_stupid: "Moi j’ai mis 2,5 millions de personnes dans la rue quand j’ai fait la réforme des retraites… Macron est un petit joueur", availability: true, rating: 3, user: usertest)
hollande = Politic.create(name: "Hollande", country: "France", description: "Vends casque de scooter peu utilisé et en très bon état, j'offre les croissants chauds avec et le contact de paparazzis", picture: "https://img.huffingtonpost.com/asset/5c937da82400003500c7e43d.jpeg?ops=scalefit_630_noupscale",
  address: "Cr 2B No. 33-06, C.P 66001 Pereira, Pereira, Colombia", first_stupid: "We can be do what we want to do", second_stupid: "Le changement c'est maintenant mdr", availability: true, rating: 2, user: usertest)
melenchon = Politic.create(name: "Mélenchon", country: "USA", description: "Tous les mardi et jeudi soir en live sur Twitch, séances ASMR et sophrologie", picture: "https://img.20mn.fr/V8ttWYtcQAqyB8-GNUOZbw/768x492_reaction-jean-luc-melenchon-agite-twitter-toute-journee.jpg",
  address: "200 Larkin St, San Francisco, CA 94102, États-Unis", first_stupid:"La république, C'EST MOI!!!", second_stupid: "Vous pouriez faire l'effort d'aller au-delà de 140 mots", availability: true, rating: 5, user: usertest)
franckunderwood = Politic.create(name:"Franck Underwood",country: "USA", description:"Vous fera voir la politic de l'interieur, la fin jusifie les moyens.", picture:"https://lubieenserie.fr/wp-content/uploads/2014/08/house-of-cards-citations-saison-1.png", address:"1243 Kenyon Street Northwest, Washington, district de Columbia 20010, États-Unis", first_stupid:"Friends make the worst enemies.", second_stupid:"“I love that woman. I love her more than sharks love blood.”", availability: true, rating: 2, user: usertest)
johnrambo= Politic.create(name:"John Rambo",country: "Vietnam", description:"Expert en négociation, il vous fera une guerre comme vous n'en avez jamais vue!", picture:"https://www.breakflip-awe.com/uploads2/Leo/2021/Septembre/john-rambo-stream-fr.jpg", address:"Trung Tâm, Huyện Lục Yên, Province de Yên Bái, Viêt Nam", first_stupid:"Tu la veux cette pu*** de guerre ?!!", second_stupid:"Adriaaaaaaannn", availability: true, rating: 2, user: usertest)
fidelcastro= Politic.create(name:"Fidel Castro",country: "Cuba", description:"Fidel Castro, the father of the Cuban Revolution, ruled his country for 47 years, from 1959 to 2006. For comparison, during that same period, 10 men served as the president of the United States.", picture:"https://cdn.britannica.com/56/195356-131-65566212/Fidel-Castro-Cuban-UN-General-Assembly-New-October-14-1979.jpg?q=60", address:"Cuba", first_stupid:"Ce qui est a toi est à moi", second_stupid:"Ce qui est a moi n'est pas à toi", availability: true, rating: 2, user: usertest)
gengiskahn= Politic.create(name:"Genghis Kahn",country:"Mongolia", description:"First man to ever use bacteriological attacks by sprading plague on his ennmies", picture:"https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/YuanEmperorAlbumGenghisPortrait.jpg/1280px-YuanEmperorAlbumGenghisPortrait.jpg", address:"Oulan-Bator, Mongolie", first_stupid:"Qui boit, meurt ; qui ne boit pas, meurt aussi...", second_stupid:"Qui ne sait pas nager ne s'aventure pas dans l'eau", availability: true, rating: 2, user: usertest)
tortueninja= Politic.create(name:"Les tortues ninjas",country:"USA", description:"À New York, Hamato Yoshi, un maître ninja japonais, est assassiné par son rival Oruku Saki. Splinter, le rat de compagnie de Yoshi1, qui a appris le ninjutsu en observant et mimant son maître, réussit à s'échapper et se réfugie dans les égouts.", picture:"https://fr.techtribune.net/wp-content/uploads/2021/08/3862985-teenage-mutant-ninja-turtles-1990.jpg", address:"100 Voice Road, Carle Place, État de New York 11514, États-Unis", first_stupid:"Kawabounga", second_stupid:"La pizza à l'ananas c'est grave bon", availability: true, rating: 2, user: usertest)
oss117= Politic.create(name: "OSS117",country:"France", description:"Avec moi, les histoires d'amour ne s'écrivent pas dans le temps, ce sont des histoires courtes, compactes, passionnelles. Je ne peux pas vivre autrement Dolorès. D'aucuns ont des aventures… Je suis une aventure.", picture:"https://img.filmsactu.net/datas/fiches/c/o/comedie/n/comedie-610a88fdcaf1e.jpg", address:"Rio de Janeiro, Rio de Janeiro, Brésil", first_stupid:"J'aime me beurrer la biscotte.", second_stupid:"À l'occasion, je vous mettrai un petit coup de polish.", availability: true, rating: 2, user: usertest)
françislalanne= Politic.create(name:"Françis Lalanne",country:"Atlantide", description: "Francis Lalanne, né le 8 août 1958 à Bayonne, est un chanteur et auteur-compositeur-interprète français, également acteur, écrivain, poète, militant politique et homme d'affaires. Il devient célèbre pour son tube On se retrouvera, bande originale du film Le Passage, en 1986", picture:"https://cdn-europe1.lanmedia.fr/var/europe1/storage/images/europe1/politique/decouvrez-le-refrain-de-la-chanson-de-francis-lalanne-sur-les-gilets-jaunes-3895989/52975091-1-fre-FR/Decouvrez-le-refrain-de-la-chanson-de-Francis-Lalanne-sur-les-gilets-jaunes.jpg", address:"Antarctique", first_stupid:"Séduire, c'est s'exposer à decevoir.", second_stupid:"C'est en leur tournant le dos que l'on triomphe des monstres qui nous habitent.", availability: true, rating: 2, user: usertest)
